### ISSUE TITLE
stat_summary_bin bug?

### ISSUE THREAD

**Issue by eipi10** [hadley/ggplot2#1739] opened 2016-09-04 21:06 UTC
In the plot below, you can see that an "extra" bin value is plotted to the right of the data values. 

```
library(ggplot2)

# simulate an example of linear data 
set.seed(1)
N <- 10^4
x <- runif(N)
y <- x + rnorm(N)
dt <- data.frame(x=x, y=y)

ggplot(dt, aes(x, y)) + 
  geom_point(alpha = 0.1, size = 0.01) +
  stat_summary_bin(fun.y=mean, bins=10, size=5, geom="point", colour="red") 
```
It seems like there could be a bug in `stat_summary_bin`, because, as shown in the code below, two y values (from the two rows with the highest x-values) are excluded from the binning and end up in an `NA` bin, which is the one plotted to the right of the data bins in the plot above. I would have expected that by default ggplot would include all the data values in the binning procedure.

```
p1=ggplot(dt, aes(x, y)) + 
  geom_point(alpha = 0.1, size = 0.01) +
  stat_summary_bin(fun.y=mean, bins=10, size=5, geom="point") +
  stat_summary_bin(fun.y=length, bins=10, size=5, geom="point")

p1b = ggplot_build(p1)
p1b$data[[2]][9:11, c(1,3,5,6)]
p1b$data[[3]][9:11, c(1,3,5,6)]
```
The issue raised above is based on [this SO question](http://stackoverflow.com/questions/39320710/ggplot-stat-summary-bin-glitch/39321019#39321019).

**Comment by thomasp85** [comment] 2016-09-05 04:55
Possible duplicate of #1651

**Comment by hadley** [comment] 2016-09-15 12:42
Simpler reprex:

```R
library(ggplot2)

x <- seq(0, 1, length = 1e2)
y <- x + rnorm(length(x))
dt <- data.frame(x, y)

# NOT OK
ggplot(dt, aes(x, y)) + 
  geom_point(colour = "grey80") +
  stat_summary_bin(fun.y=mean, bins=10, geom = "point", colour = "red") 

# OK
ggplot(dt, aes(x)) + 
  geom_histogram(bins = 10, boundary = 0)
```

**Comment by hadley** [comment] 2016-09-15 12:48
That's not an NA bin, it's the bin `[1.0, 1.1)`.  This just an unfortunately consequence of the fact that you can't exactly represent 1 / 10 = 0.1 as a floating point number.

**Closed by hadley** 2016-09-15 12:48 UTC

**Comment by eipi10** [comment] 2016-09-15 15:39
Thanks Hadley.
