### ISSUE TITLE
theme_classic() no axis lines in version 2.1

### ISSUE THREAD

**Issue by jscamac** [hadley/ggplot2#1565] opened 2016-03-02 02:29 UTC
Shouldn't theme_classic actually have axis lines?
Is the update a mistake?

See theme_classic():
http://docs.ggplot2.org/dev/ggtheme.html

**Comment by Katiedaisey** [comment] 2016-03-02 23:02
It seems my update to allow access to lower level elements (axis.line.x, panel.grid.major.y, etc) leaves changes to upper level elements unused.  Let me give this some thought.

**Comment by steveharoz** [comment] 2016-03-03 02:21
Here's a temporary workaround for the axes if anyone needs it until the issue's resolved:
    theme_classic() + theme(
        axis.line.x = element_line(colour = 'black', size=0.5, linetype='solid'),
        axis.line.y = element_line(colour = 'black', size=0.5, linetype='solid'))

**Comment by jscamac** [comment] 2016-03-03 02:49
Thanks. I already had the work around but thought I should let you know of the changes to the classic_theme.

**Comment by ustervbo** [comment] 2016-03-05 16:08
I think the problem is related to https://github.com/hadley/ggplot2/issues/1567 and seems to stem from  complete removal of axis lines by default

**Comment by Katiedaisey** [comment] 2016-03-05 16:27
It has to do with how attributes for elements are inherited.  To remove an attribute, like axis.line in some themes, the current code sets them as element_blank(). However if a subelement, axis.line.x and axis.line.y are added, they inherit element_blank and will not appear. Newly added elements need to inherit from the original object (line, rect, or text) skipping any blank elements but I'm still thinking on how to do that.

**Comment by bklingen** [comment] 2016-03-09 14:45
Really would appreciate for theme_classic() to work as in version 2.0.0 (and all prior versions), showing the x and y axis line as before instead of drawing no axis at all. (And thanks for the, hopefully temporary, workaround). I have countless shiny applications that depend on the classic theme, and re-programming all of these would be a nightmare.

**Comment by Katiedaisey** [comment] 2016-03-09 22:09
I think I have this completely fixed.  Would anyone mind testing before I request a pull?

**Comment by steveharoz** [comment] 2016-03-09 22:35
I pulled from your fork and tried running the example in http://docs.ggplot2.org/current/ggtheme.html
The ticks and labels look messed up, but I'm not sure if it's related.

```
ggplot(mtcars) + 
  geom_point(aes(x = wt, y = mpg, colour=factor(gear))) + 
  facet_wrap(~am) +
  theme_classic()
```
![image](https://cloud.githubusercontent.com/assets/2257540/13652944/9d1c5d2a-e614-11e5-9c92-4a53d43a7a89.png)

Nevertheless, axis lines appear to work:
```
ggplot(mtcars, aes(wt, mpg)) +
  geom_point() +
  theme(axis.line=element_line())
```
![image](https://cloud.githubusercontent.com/assets/2257540/13652989/d570be96-e614-11e5-8539-bbef8906a471.png)

**Comment by Katiedaisey** [comment] 2016-03-10 00:31
@steveharoz The ticks and labels were affected.  They should also be fixed now.

**Comment by steveharoz** [comment] 2016-03-10 00:56
Nice! Looks like it's fixed.

Here are the graphs with latest commit:
![image](https://cloud.githubusercontent.com/assets/2257540/13655744/66926124-e627-11e5-9d5b-ab03a55aa7b8.png)
 ![image](https://cloud.githubusercontent.com/assets/2257540/13655734/5074cee0-e627-11e5-91aa-6153e542db6a.png)

Looks identical to commit a760ff627582da59f938af14b0f01d54a4a97aa7 (right before the theme updates)
![image](https://cloud.githubusercontent.com/assets/2257540/13655844/1823f5ce-e628-11e5-9618-3ecc0d1ee574.png) 
![image](https://cloud.githubusercontent.com/assets/2257540/13655865/34dd0390-e628-11e5-83ea-447fa51bfabb.png)

**Comment by sjin09** [comment] 2016-03-28 09:33
Dear Katiedaisy,

I have recently downloaded the ggplot2 again to my desktop and found that the theme_classic() does not draw the axis.line() and I have come across this post. I have tried as shown by steveharoz. 

ggplot(mtcars, aes(wt, mpg)) +
  geom_point() +
  theme(axis.line=element_line())

Would this problem be addressed again?

Many Thanks,
Jin

**Comment by Katiedaisey** [comment] 2016-03-28 13:44
Hi sjin09
You downloaded ggplot2 from CRAN or from my git? The fix has not yet been added to the package available on CRAN.

**Comment by ecp52** [comment] 2016-05-19 23:01
Wizards of ggplot, I also have this problem, that the axes are not drawn even after downloading the package from this site.
Very grateful for your work on this! 
![image](https://cloud.githubusercontent.com/assets/19480240/15412253/22dc61be-1df4-11e6-8c20-5cd36ba56e03.png)

**Comment by ecp52** [comment] 2016-05-19 23:09
OK, had to get rid of the old version-- works great now!
Thanks for your hard work!
![image](https://cloud.githubusercontent.com/assets/19480240/15412410/400d66e2-1df5-11e6-860f-9887cf4db147.png)

**Comment by bklingen** [comment] 2016-06-08 21:13
I still don't get axis lines:

ggplot(mtcars) + geom_point() + theme_classic()

**Comment by jac0bean9** [comment] 2016-07-08 15:55
I'm having the same trouble, even after specifically requesting a grid. For example:

`ggplot(mtcars, aes(wt, mpg)) + geom_point() + theme_classic() + theme(panel.grid.major = element_line(colour='red'))
`

**Comment by rpruim** [comment] 2016-07-08 18:17
This issue does not appear to be fixed in

```
 ggplot2    * 2.1.0       2016-07-08 Github (hadley/ggplot2@b181e9a) 
```
I get the following:
```r
ggplot(aes(x = eruptions), data = faithful) + geom_histogram() + theme_classic()
```
![image](https://cloud.githubusercontent.com/assets/722231/16697180/77e5060e-4516-11e6-9ad4-65de50b6441a.png)

**Comment by steveharoz** [comment] 2016-07-08 18:23
@Katiedaisey: Have you made a pull request with your fix?

**Comment by Katiedaisey** [comment] 2016-07-12 14:05
@steveharoz: yes. It hasn't been integrated yet. No idea what's going on.

@jac0bean9 @rpruim: This has been fixed in my pull request #1581 and as available on my git. It just hasn't been integrated yet.

**Comment by assaforon** [comment] 2016-07-20 18:16
@Katiedaisey thank you so much for the fix. I am actually under a crunch to use it, as the PI in my study wants precisely the classical layout (black axes, no borders) for a rather elaborage 4x2 grid of ggplots I've written for an article we're submitting. 
Being a novice Git user, I just copy-pasted the relevant functions you've modified in your edits, and am sourcing them directly after loading ggplot2. That didn't work. I changed the theme to 'theme_classic0', inheriting from 'theme_bw0'. Still doesn't work. I do see that the theme is defined as you had set it, but for some reason the output is still no axes rather than black ones.
How can I build ggplot2 from your edit rather than from the official one? Or any other advice as to how to make this work ASAP?

Thanks a bunch!
Assaf

**Comment by rpruim** [comment] 2016-07-20 18:20
It's a one-liner if you have devtools installed.  A two-liner if not:
```r
install.packages("devtools")
devtools::install_github("Katiedaisey/ggplot2")
```

**Comment by assaforon** [comment] 2016-07-20 18:35
Wow, it works now! Thank you both @rpruim @Katiedaisey.
I do use devtools, in fact I have 2 packages right here on GitHub, one of which ('cir') is only available via install_github() at the moment. 
But I didn't realize Katie actually had a full working version of ggplot2 on her account. A very novice Git user, as I said ;)

Anyway, all's well that ends well. How can we up the pressure on Hadley et al. to finally integrate this?

**Comment by Katiedaisey** [comment] 2016-07-20 19:07
@assaforon Hope it works out for you. I'll look at updating the package on my account to the most recent version of ggplot2 incase there's any of the newer changes you need.

**Comment by hadley** [comment] 2016-07-29 12:56
Duplicate of #1567

**Closed by hadley** 2016-07-29 12:56 UTC
