### ISSUE TITLE
v2.2.0 error: can't add vline or hline to a faceted plot

### ISSUE THREAD

**Issue by daattali** [hadley/ggplot2#1834] opened 2016-10-06 00:24 UTC
I didn't debug enough to figure out exactly when it does or doesn't happen, but I have a fairly minimal case where the bug shows.

```
library(ggplot2)
df <- data.frame(x = 1:4, y = 1:4, row = c(1,1,2,2), col = c(1,2,1,2))
ggplot(df, aes(x,y)) + geom_point() + facet_grid(row~col)          # works
ggplot(df, aes(x,y)) + geom_point() + geom_vline(xintercept = 3)     # works
ggplot(df, aes(x,y)) + geom_point() + facet_grid(row~col) + geom_vline(xintercept = 3)   # ERROR
```

The last line does not work in the new ggplot2 version.  It did previously.  I get the error

```
Error in column[rows] <<- what : 
  incompatible types (from closure to double) in subassignment type fix
```

**Comment by hadley** [comment] 2016-10-06 13:51
Appears to be a duplicate of #1803 because after fixing that it now works :)

**Closed by hadley** 2016-10-06 13:51 UTC
Labels: bug
