### ISSUE TITLE
Control justification of legends

### ISSUE THREAD

**Issue by hadley** [hadley/ggplot2#1716] opened 2016-08-16 18:41 UTC
I'm not sure why there's currently no way to do this. Is this what `legend.box.just` is supposed to control?

I think the default would look nicer if the legends were left/top aligned to the panel area.

**Comment by thomasp85** [comment] 2016-08-16 18:53
I can't decipher the meaning of `legend.box.just` from the docs, but apparently it only has an effect with multiple legends...

**Comment by thomasp85** [comment] 2016-08-22 09:43
Ok, legend.box.just is never used, beyond setting its default value (it is never accessed during build)

Can we repurpose this theme setting for your request?

Also, I understand you correctly in that the justification should be relative to the plotting region and not the full region? (`legend.box.just = "top"` should make the legend flush with the topmost panel)

**Comment by thomasp85** [comment] 2016-08-22 09:46
scratch that - "find in files" is messing up

**Comment by thomasp85** [comment] 2016-08-22 10:00
Oh, now i get it - it's for their internal alignment...

look at the difference:
```r
ggplot(mtcars) + 
  geom_point(aes(x = cyl, y = mpg, colour = gear, size = hp)) + 
  theme(legend.box.just = 'left') + 
  scale_size_area(max_size = 20)

ggplot(mtcars) + 
  geom_point(aes(x = cyl, y = mpg, colour = gear, size = hp)) + 
  theme(legend.box.just = 'right') + 
  scale_size_area(max_size = 20)
```

You get dibs on the name for the theme option to control their overall alignment though I think `legend.just` would make sense

**Comment by thomasp85** [comment] 2016-08-22 10:20
Digging deeper - there is a `legend.justification` theme option that is intended for this. The problem is that it sets the justification relative to the viewport and since the viewport itself doesn't have any size the justification doesn't have an effect.

My recommendation would be to fix this by generalising @baptiste solution in http://stackoverflow.com/questions/25327875/is-it-possible-to-position-the-legend-to-the-top-right-of-a-ggplot-in-r/38992407#38992407 and add a row above and below the legends in the legends gtable with a `null` size that pushes the legend upwards or downwards...

thoughts?

**Comment by hadley** [comment] 2016-08-22 14:38
Can't we set the size of the viewport to span the full height/width of the panels viewport?

**Comment by thomasp85** [comment] 2016-08-22 19:27
There you go (#1724)

**Comment by baptiste** [comment] 2016-08-23 07:49
For what it's worth, I've recently arrived to the conclusion that a 3x3 layout to set ltrb margins around a given graphic element is a convenient alternative to justification (albeit at the price of a slightly deeper internal structure). Justification with grid viewports is always a pain because one needs to specify x,y, and just, but also the anchor point, and I find the combination needlessly unintuitive, especially when the user doesn't have access to the object's dimensions. Thinking in terms of margins has a more straight-forward meaning.

That's what I've experimented with in the [egg package](https://github.com/baptiste/egg#aligning-complex-ggplots) to combine arbitrary ggplots, so that the panels are aligned, regardless of facets and legends. 
For legends, this approach would basically boil down to the solution I proposed on SO, but the theme would set the defaults. Top alignment would be 0-guide-1null, centre 1null-guide-1null, etc.

**Comment by thomasp85** [comment] 2016-08-23 07:53
I tend to agree with you, though I've fixed it based on a native viewport approach for now...

I'll try out both and see which ones makes for the cleanest implementation

**Comment by baptiste** [comment] 2016-08-23 07:58
Besides a clean implementation, it could be nice to also consider extensibility: currently it's rather hard to access the legend, manipulate it, add to it, etc. I understand it's partly by design, so that no-one messes with the automated mapping, but it would still be nice to be able to tweak things more easily, e.g. add custom graphical elements to a legend, combine legends from multiple plots, etc.

**Comment by thomasp85** [comment] 2016-08-23 08:00
Could this be fixed with a simple extractor function (like e.g. `layer_scales()`) that returns a list of legend grobs?

**Comment by kohske** [comment] 2016-08-23 08:08
Hi, although I haven't been able to follow the recent development of ggplot2, the things were really complicated when I wrote some parts of codes a few years ago. It would be nice if there is a way to control the justification of legend box more flexibly (but is this really impossible now?).

Also, IIRC there was a discussion about manual tweaking of legends some years ago, and finally the idea was rejected due to the policy of ggplot2, i.e., data visualization is not the painting of figure.

But the situation is changing now, so we may have the way to tweak legends...

I hope the next version will have the nicer legend system :)

**Comment by thomasp85** [comment] 2016-08-23 08:13
I think the legend system will at least get a rewrite to ggproto at some point (probably not the next version), but whether this will be a purely mechanical transition or if there will be any rewrite done is unknown (might not be me doing it)...

It is also true that some of the constraints are there by design and a thorough discussion is needed before we open up this bag of hurt :-)

Currently it is possible to add your own legend specs (eg guide_direction from ggraph) so adventurous developers are completely free to do as they please...

**Comment by thomasp85** [comment] 2016-08-23 08:29
Ok - there are now two different approaches to this:

#1724 Implements it using native viewport justification
#1725 Implements it by adding rows and columns around the legend gtable

Comment on either approach is appreciated, as well as a final say from @hadley

**Comment by thomasp85** [comment] 2016-08-23 08:35
With either implementation we might want the user to control the margin around the legend box separately from the margin between each legend (e.g. a user might want no margin around the legend box when aligned with top, but still wants the individual legends to be separated by a spacer)

**Closed** 2016-09-09 11:11 UTC
Labels: in progress
