### ISSUE TITLE
Error in as.character(what) :    cannot coerce type 'closure' to vector of type 'character'

### ISSUE THREAD

**Issue by carloscinelli** [hadley/ggplot2#1832] opened 2016-10-05 17:54 UTC
Hi, guys,

I just received Hadley's email about the new ggplot2 release and did some tests. This is a minimal reproducible example of the error I could come up with.

So first download this file with a ggplot object:

https://drive.google.com/file/d/0B176voaLE9E1bTVZQlJVYmVaelU/view?usp=sharing

And read it:

`p <- readRDS("p.rds")`

This plot works fine:
`print(p)`
![ggplotbug](https://cloud.githubusercontent.com/assets/5638899/19125067/86feba8a-8aea-11e6-9b4a-fe14244b7dd0.png)

However, if you add `geom_hline()` and try to print it again, it throws an error:

`p + geom_hline(yintercept = 0)`

> Error in as.character(what) : 
>   cannot coerce type 'closure' to vector of type 'character'

**Comment by thomasp85** [comment] 2016-10-05 18:01
Can you share how the ggplot2 object came into being?

**Comment by carloscinelli** [comment] 2016-10-05 18:13
It's one of the tests I do for the sValues package: https://github.com/carloscinelli/sValues/blob/master/tests/testthat/test-sValues.R

**Comment by carloscinelli** [comment] 2016-10-05 18:13
But I would guess the ggplot object has all meta information you guys need, right?

**Comment by hadley** [comment] 2016-10-05 18:29
A minimal reprex would be better, but I'm almost 100% sure it's a duplicate of #1822

**Closed by hadley** 2016-10-05 18:29 UTC

**Comment by carloscinelli** [comment] 2016-10-05 19:07
Thanks, I will follow #1822
