### ISSUE TITLE
fixed value for height in geom_tile 

### ISSUE THREAD

**Issue by HLindsay** [hadley/ggplot2#1496] opened 2016-01-14 18:13 UTC
Setting a fixed value for "height" outside the aes call in geom_tile no longer works for me with ggplot2_2.0.0 and R 3.2.2.

```R
library(ggplot2)
dat <- data.frame(x = rep(c(1,2), each = 2), y = rep(c("A", "B"), 2))

# This fails with error message 
# Error: Unknown parameters: height
ggplot(dat, aes(x = x, y = y)) + geom_tile(height = 0.5)

# This works
ggplot(dat, aes(x = x, y = y)) + geom_tile(aes(height = 0.5))
```
However, setting a fixed value for "fill" outside the aes call still works

```R
ggplot(dat, aes(x = x, y = y)) + geom_tile(fill = "blue")
```
Is there something wrong here?

**Comment by hadley** [comment] 2016-01-25 16:26
Duplicate of #1513

**Closed by hadley** 2016-01-25 16:26 UTC
