### ISSUE TITLE
geom_bar fill ignores order of factor's levels.

### ISSUE THREAD

**Issue by DasHammett** [hadley/ggplot2#1301] opened 2015-08-28 18:18 UTC
Hi!

I am having an issue with geom_bar when I pass the fill parameter to ggplot aes. The order of filling is done alphabetically, ignoring the levels.

I have tried to pass ```order``` parameter to ggplot aes and it solves the issue, but then geom_text is misaligned.

On a side note, Positions for geom_text are done after leveling is set.

I share a ```head``` of the dput for reproducibility purposes. This is a sample of a satisfaction survey, hence the importance of having the correct order of filling up the bars.
```
structure(list(value = structure(c(2L, 3L, 4L, 1L, 5L, 2L, 3L, 
4L, 1L, 5L, 2L, 3L, 4L, 1L, 5L, 2L, 3L, 4L, 1L, 5L, 2L, 3L, 4L, 
1L, 5L, 2L, 3L, 4L, 1L, 5L, 2L, 3L, 4L, 1L, 5L, 2L, 3L, 4L, 1L, 
5L, 2L, 3L, 4L, 1L, 5L, 2L, 3L, 4L, 1L, 5L, 2L, 3L, 4L, 1L, 5L, 
2L, 3L, 4L, 1L, 5L, 2L, 3L, 4L, 1L, 5L, 2L, 3L, 4L, 1L, 5L, 2L, 
3L, 4L, 1L, 5L, 2L, 3L, 4L, 1L, 5L), .Label = c("Very dissatisfied", 
"Dissatisfied", "Neutral", "Satisfied", "Very satisfied"), class = "factor"), 
    site = c("Barcelona", "Barcelona", "Barcelona", "Barcelona", 
    "Barcelona", "Barcelona", "Barcelona", "Barcelona", "Barcelona", 
    "Barcelona", "Barcelona", "Barcelona", "Barcelona", "Barcelona", 
    "Barcelona", "Barcelona", "Barcelona", "Barcelona", "Barcelona", 
    "Barcelona", "Barcelona", "Barcelona", "Barcelona", "Barcelona", 
    "Barcelona", "Barcelona", "Barcelona", "Barcelona", "Barcelona", 
    "Barcelona", "Barcelona", "Barcelona", "Barcelona", "Barcelona", 
    "Barcelona", "Barcelona", "Barcelona", "Barcelona", "Barcelona", 
    "Barcelona", "Lisbon", "Lisbon", "Lisbon", "Lisbon", "Lisbon", 
    "Lisbon", "Lisbon", "Lisbon", "Lisbon", "Lisbon", "Lisbon", 
    "Lisbon", "Lisbon", "Lisbon", "Lisbon", "Lisbon", "Lisbon", 
    "Lisbon", "Lisbon", "Lisbon", "Lisbon", "Lisbon", "Lisbon", 
    "Lisbon", "Lisbon", "Lisbon", "Lisbon", "Lisbon", "Lisbon", 
    "Lisbon", "Lisbon", "Lisbon", "Lisbon", "Lisbon", "Lisbon", 
    "Lisbon", "Lisbon", "Lisbon", "Lisbon", "Lisbon"), variable = c("Is the TMS Team approachable ", 
    "Is the TMS Team approachable ", "Is the TMS Team approachable ", 
    "Is the TMS Team approachable ", "Is the TMS Team approachable ", 
    "They give you the chance to listen to your call ", "They give you the chance to listen to your call ", 
    "They give you the chance to listen to your call ", "They give you the chance to listen to your call ", 
    "They give you the chance to listen to your call ", "They fairly evaluate your calls ", 
    "They fairly evaluate your calls ", "They fairly evaluate your calls ", 
    "They fairly evaluate your calls ", "They fairly evaluate your calls ", 
    "They explain in detail the result of your call ", "They explain in detail the result of your call ", 
    "They explain in detail the result of your call ", "They explain in detail the result of your call ", 
    "They explain in detail the result of your call ", "They are knowledgeable about H2H ", 
    "They are knowledgeable about H2H ", "They are knowledgeable about H2H ", 
    "They are knowledgeable about H2H ", "They are knowledgeable about H2H ", 
    "They reinforce the 3As approach and importance ", "They reinforce the 3As approach and importance ", 
    "They reinforce the 3As approach and importance ", "They reinforce the 3As approach and importance ", 
    "They reinforce the 3As approach and importance ", "They give effective coaching to help you improve your NS results  including H2H and 3As ", 
    "They give effective coaching to help you improve your NS results  including H2H and 3As ", 
    "They give effective coaching to help you improve your NS results  including H2H and 3As ", 
    "They give effective coaching to help you improve your NS results  including H2H and 3As ", 
    "They give effective coaching to help you improve your NS results  including H2H and 3As ", 
    "What is the overall satisfaction regarding the TMS Team  ", 
    "What is the overall satisfaction regarding the TMS Team  ", 
    "What is the overall satisfaction regarding the TMS Team  ", 
    "What is the overall satisfaction regarding the TMS Team  ", 
    "What is the overall satisfaction regarding the TMS Team  ", 
    "Is the TMS Team approachable ", "Is the TMS Team approachable ", 
    "Is the TMS Team approachable ", "Is the TMS Team approachable ", 
    "Is the TMS Team approachable ", "They give you the chance to listen to your call ", 
    "They give you the chance to listen to your call ", "They give you the chance to listen to your call ", 
    "They give you the chance to listen to your call ", "They give you the chance to listen to your call ", 
    "They fairly evaluate your calls ", "They fairly evaluate your calls ", 
    "They fairly evaluate your calls ", "They fairly evaluate your calls ", 
    "They fairly evaluate your calls ", "They explain in detail the result of your call ", 
    "They explain in detail the result of your call ", "They explain in detail the result of your call ", 
    "They explain in detail the result of your call ", "They explain in detail the result of your call ", 
    "They are knowledgeable about H2H ", "They are knowledgeable about H2H ", 
    "They are knowledgeable about H2H ", "They are knowledgeable about H2H ", 
    "They are knowledgeable about H2H ", "They reinforce the 3As approach and importance ", 
    "They reinforce the 3As approach and importance ", "They reinforce the 3As approach and importance ", 
    "They reinforce the 3As approach and importance ", "They reinforce the 3As approach and importance ", 
    "They give effective coaching to help you improve your NS results  including H2H and 3As ", 
    "They give effective coaching to help you improve your NS results  including H2H and 3As ", 
    "They give effective coaching to help you improve your NS results  including H2H and 3As ", 
    "They give effective coaching to help you improve your NS results  including H2H and 3As ", 
    "They give effective coaching to help you improve your NS results  including H2H and 3As ", 
    "What is the overall satisfaction regarding the TMS Team  ", 
    "What is the overall satisfaction regarding the TMS Team  ", 
    "What is the overall satisfaction regarding the TMS Team  ", 
    "What is the overall satisfaction regarding the TMS Team  ", 
    "What is the overall satisfaction regarding the TMS Team  "
    ), score = c(0.0431034482758621, 0.129310344827586, 0.413793103448276, 
    0.0258620689655172, 0.387931034482759, 0.0431034482758621, 
    0.293103448275862, 0.310344827586207, 0.0603448275862069, 
    0.293103448275862, 0.0603448275862069, 0.198275862068966, 
    0.387931034482759, 0.0431034482758621, 0.310344827586207, 
    0.0172413793103448, 0.155172413793103, 0.413793103448276, 
    0.0258620689655172, 0.387931034482759, 0.0258620689655172, 
    0.103448275862069, 0.379310344827586, 0.0258620689655172, 
    0.46551724137931, 0.0172413793103448, 0.0948275862068965, 
    0.336206896551724, 0.0258620689655172, 0.525862068965517, 
    0.0344827586206897, 0.146551724137931, 0.318965517241379, 
    0.0344827586206897, 0.46551724137931, 0.0344827586206897, 
    0.181034482758621, 0.336206896551724, 0.0258620689655172, 
    0.422413793103448, 0.0628930817610063, 0.270440251572327, 
    0.383647798742138, 0.0377358490566038, 0.245283018867925, 
    0.119496855345912, 0.364779874213836, 0.232704402515723, 
    0.10062893081761, 0.182389937106918, 0.0880503144654088, 
    0.19496855345912, 0.446540880503145, 0.0314465408805031, 
    0.238993710691824, 0.0691823899371069, 0.138364779874214, 
    0.452830188679245, 0.0251572327044025, 0.314465408805031, 
    0.0314465408805031, 0.182389937106918, 0.427672955974843, 
    0.0251572327044025, 0.333333333333333, 0.0377358490566038, 
    0.132075471698113, 0.427672955974843, 0.0125786163522013, 
    0.389937106918239, 0.0566037735849057, 0.207547169811321, 
    0.364779874213836, 0.050314465408805, 0.320754716981132, 
    0.0628930817610063, 0.19496855345912, 0.408805031446541, 
    0.0440251572327044, 0.289308176100629), Position = c(0.021551724137931, 
    0.107758620689655, 0.379310344827586, 0.599137931034483, 
    0.806034482758621, 0.021551724137931, 0.189655172413793, 
    0.491379310344828, 0.676724137931034, 0.853448275862069, 
    0.0301724137931034, 0.15948275862069, 0.452586206896552, 
    0.668103448275862, 0.844827586206897, 0.00862068965517241, 
    0.0948275862068966, 0.379310344827586, 0.599137931034483, 
    0.806034482758621, 0.0129310344827586, 0.0775862068965517, 
    0.318965517241379, 0.521551724137931, 0.767241379310345, 
    0.00862068965517241, 0.0646551724137931, 0.280172413793103, 
    0.461206896551724, 0.737068965517241, 0.0172413793103448, 
    0.107758620689655, 0.34051724137931, 0.517241379310345, 0.767241379310345, 
    0.0172413793103448, 0.125, 0.383620689655172, 0.564655172413793, 
    0.788793103448276, 0.0314465408805031, 0.19811320754717, 
    0.525157232704403, 0.735849056603774, 0.877358490566038, 
    0.059748427672956, 0.30188679245283, 0.60062893081761, 0.767295597484277, 
    0.908805031446541, 0.0440251572327044, 0.185534591194969, 
    0.506289308176101, 0.745283018867925, 0.880503144654088, 
    0.0345911949685535, 0.138364779874214, 0.433962264150943, 
    0.672955974842767, 0.842767295597484, 0.0157232704402516, 
    0.122641509433962, 0.427672955974843, 0.654088050314465, 
    0.833333333333333, 0.0188679245283019, 0.10377358490566, 
    0.383647798742138, 0.60377358490566, 0.805031446540881, 0.0283018867924528, 
    0.160377358490566, 0.446540880503145, 0.654088050314465, 
    0.839622641509434, 0.0314465408805031, 0.160377358490566, 
    0.462264150943396, 0.688679245283019, 0.855345911949686), 
    variable2 = c("Is the TMS Team\napproachable", "Is the TMS Team\napproachable", 
    "Is the TMS Team\napproachable", "Is the TMS Team\napproachable", 
    "Is the TMS Team\napproachable", "They give you\nthe chance to\nlisten to your\ncall", 
    "They give you\nthe chance to\nlisten to your\ncall", "They give you\nthe chance to\nlisten to your\ncall", 
    "They give you\nthe chance to\nlisten to your\ncall", "They give you\nthe chance to\nlisten to your\ncall", 
    "They fairly\nevaluate your\ncalls", "They fairly\nevaluate your\ncalls", 
    "They fairly\nevaluate your\ncalls", "They fairly\nevaluate your\ncalls", 
    "They fairly\nevaluate your\ncalls", "They explain\nin detail the\nresult of your\ncall", 
    "They explain\nin detail the\nresult of your\ncall", "They explain\nin detail the\nresult of your\ncall", 
    "They explain\nin detail the\nresult of your\ncall", "They explain\nin detail the\nresult of your\ncall", 
    "They are\nknowledgeable\nabout H2H", "They are\nknowledgeable\nabout H2H", 
    "They are\nknowledgeable\nabout H2H", "They are\nknowledgeable\nabout H2H", 
    "They are\nknowledgeable\nabout H2H", "They reinforce\nthe 3As\napproach and\nimportance", 
    "They reinforce\nthe 3As\napproach and\nimportance", "They reinforce\nthe 3As\napproach and\nimportance", 
    "They reinforce\nthe 3As\napproach and\nimportance", "They reinforce\nthe 3As\napproach and\nimportance", 
    "They give\neffective\ncoaching\nto help you\nimprove your\nNS results\nincluding H2H\nand 3As", 
    "They give\neffective\ncoaching\nto help you\nimprove your\nNS results\nincluding H2H\nand 3As", 
    "They give\neffective\ncoaching\nto help you\nimprove your\nNS results\nincluding H2H\nand 3As", 
    "They give\neffective\ncoaching\nto help you\nimprove your\nNS results\nincluding H2H\nand 3As", 
    "They give\neffective\ncoaching\nto help you\nimprove your\nNS results\nincluding H2H\nand 3As", 
    "What is\nthe overall\nsatisfaction\nregarding the\nTMS Team", 
    "What is\nthe overall\nsatisfaction\nregarding the\nTMS Team", 
    "What is\nthe overall\nsatisfaction\nregarding the\nTMS Team", 
    "What is\nthe overall\nsatisfaction\nregarding the\nTMS Team", 
    "What is\nthe overall\nsatisfaction\nregarding the\nTMS Team", 
    "Is the TMS Team\napproachable", "Is the TMS Team\napproachable", 
    "Is the TMS Team\napproachable", "Is the TMS Team\napproachable", 
    "Is the TMS Team\napproachable", "They give you\nthe chance to\nlisten to your\ncall", 
    "They give you\nthe chance to\nlisten to your\ncall", "They give you\nthe chance to\nlisten to your\ncall", 
    "They give you\nthe chance to\nlisten to your\ncall", "They give you\nthe chance to\nlisten to your\ncall", 
    "They fairly\nevaluate your\ncalls", "They fairly\nevaluate your\ncalls", 
    "They fairly\nevaluate your\ncalls", "They fairly\nevaluate your\ncalls", 
    "They fairly\nevaluate your\ncalls", "They explain\nin detail the\nresult of your\ncall", 
    "They explain\nin detail the\nresult of your\ncall", "They explain\nin detail the\nresult of your\ncall", 
    "They explain\nin detail the\nresult of your\ncall", "They explain\nin detail the\nresult of your\ncall", 
    "They are\nknowledgeable\nabout H2H", "They are\nknowledgeable\nabout H2H", 
    "They are\nknowledgeable\nabout H2H", "They are\nknowledgeable\nabout H2H", 
    "They are\nknowledgeable\nabout H2H", "They reinforce\nthe 3As\napproach and\nimportance", 
    "They reinforce\nthe 3As\napproach and\nimportance", "They reinforce\nthe 3As\napproach and\nimportance", 
    "They reinforce\nthe 3As\napproach and\nimportance", "They reinforce\nthe 3As\napproach and\nimportance", 
    "They give\neffective\ncoaching\nto help you\nimprove your\nNS results\nincluding H2H\nand 3As", 
    "They give\neffective\ncoaching\nto help you\nimprove your\nNS results\nincluding H2H\nand 3As", 
    "They give\neffective\ncoaching\nto help you\nimprove your\nNS results\nincluding H2H\nand 3As", 
    "They give\neffective\ncoaching\nto help you\nimprove your\nNS results\nincluding H2H\nand 3As", 
    "They give\neffective\ncoaching\nto help you\nimprove your\nNS results\nincluding H2H\nand 3As", 
    "What is\nthe overall\nsatisfaction\nregarding the\nTMS Team", 
    "What is\nthe overall\nsatisfaction\nregarding the\nTMS Team", 
    "What is\nthe overall\nsatisfaction\nregarding the\nTMS Team", 
    "What is\nthe overall\nsatisfaction\nregarding the\nTMS Team", 
    "What is\nthe overall\nsatisfaction\nregarding the\nTMS Team"
    )), .Names = c("value", "site", "variable", "score", "Position", 
"variable2"), row.names = c(NA, 80L), vars = list(variable), labels = structure(list(
    variable = structure(1:8, .Label = c("Is.the.TMS.Team.approachable.", 
    "They.give.you.the.chance.to.listen.to.your.call.", "They.fairly.evaluate.your.calls.", 
    "They.explain.in.detail.the.result.of.your.call.", "They.are.knowledgeable.about.H2H.", 
    "They.reinforce.the.3As.approach.and.importance.", "They.give.effective.coaching.to.help.you.improve.your.NS.results..including.H2H.and.3As.", 
    "What.is.the.overall.satisfaction.regarding.the.TMS.Team.."
    ), class = "factor")), class = "data.frame", row.names = c(NA, 
-8L), .Names = "variable", vars = list(variable)), indices = list(
    0:4, 5:9, 10:14, 15:19, 20:24, 25:29, 30:34, 35:39), class = c("grouped_df", 
"tbl_df", "tbl", "data.frame"))
```
The code to reproduce the chart is:
```
ggplot(table.merged,aes(variable2,score,fill=value))+
  geom_bar(stat="identity",alpha=0.6,colour="grey60")+
  geom_text(aes(label=round(score,2),y=table.merged$Position),colour="white")+
  facet_wrap(~site)+
  scale_fill_manual(values=c("darkred","red","orange","green","darkgreen"))+
  labs(title="General satisfaction with TMS", y="Percentage",x="")+
  theme(plot.title=element_text(vjust=1),
        legend.position="top",
        legend.title=element_blank()) 
```
Thank you

**Comment by hadley** [comment] 2015-08-29 11:29
The problem is this: `table.merged$Position`.

**Closed by hadley** 2015-08-29 11:29 UTC

**Comment by DasHammett** [comment] 2015-08-29 13:30
Position of ```geom_text``` is irrelevant to the fact that bar fills alphabetically instead of following levels.
I have workarround it by arranging the categorical variable according to levels.

**Comment by DasHammett** [comment] 2015-08-29 15:08
Hi!
Thanks for answering

If I remove geom_text from the ggplot, the issue still persists.
![ggplot](https://cloud.githubusercontent.com/assets/13760961/9562599/9372679c-4e70-11e5-8a3a-a1c77bae6cc2.png)

**Comment by hadley** [comment] 2015-08-29 19:45
If you prepare a _minimal_ example I can take a look but there's too much extraneous detail in your current code.

**Comment by DasHammett** [comment] 2015-08-29 22:05
Hi!

Please see a minimal example. I hope it makes things easier and cleaner

```
library(reshape2)

### Prepare some toy data
satisfaction <- c("Very dissatisfied","Dissatisfied","Neutral","Satisfied","Very satisfied")
df <- data.frame(matrix(sample(satisfaction,60,replace = T),nrow=12))
colnames(df) <- c(paste("Q",1:5,sep=""))

### Melt data to get the counts and set the appropriate levels
df.melt <- melt(df,measure.vars = c(1:ncol(df))) %>% count(value,variable)
df.melt$value <- factor(df.melt$value,levels=c(satisfaction))

### Plot
ggplot(df.melt,aes(variable,n,fill=value))+
  geom_bar(stat="identity")+
  scale_fill_manual(values=c("darkred","red","orange","green","darkgreen"))
```
Thank you

**Comment by jonathan-g** [comment] 2015-12-25 10:28
I am seeing the same problem.

     library(tidyr)
     library(dplyr)
     library(ggplot2)
     satisfaction <- c("Very dissatisfied","Dissatisfied","Neutral","Satisfied","Very satisfied")
     df <- data.frame(matrix(sample(satisfaction,60,replace = T),nrow=12))
     colnames(df) <- c(paste0("Q",1:5))
     df <- gather(df, key = q, value = sat) %>% group_by(q, sat) %>% summarize(count = n()) %>% 
          ungroup() %>% mutate(sat = ordered(sat, levels = satisfaction))
     ggplot(df, aes(x = q, y = count, fill = sat)) + geom_bar(stat='identity')

![rplot01](https://cloud.githubusercontent.com/assets/5304060/12002235/09fbaba8-aabf-11e5-8e66-44e83e481358.png)

    sessionInfo()

        R version 3.2.3 (2015-12-10)
    Platform: x86_64-w64-mingw32/x64 (64-bit)
    Running under: Windows >= 8 x64 (build 9200)
    
    locale:
    [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252          LC_MONETARY=English_United States.1252
    [4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     

    other attached packages:
    [1] ggplot2_2.0.0 dplyr_0.4.3   tidyr_0.3.1  

    loaded via a namespace (and not attached):
     [1] Rcpp_0.12.2      digest_0.6.8     assertthat_0.1   grid_3.2.3       R6_2.1.1         plyr_1.8.3       gtable_0.1.2     DBI_0.3.1       
     [9] magrittr_1.5     scales_0.3.0     lazyeval_0.1.10  labeling_0.3     tools_3.2.3      munsell_0.4.2    parallel_3.2.3   colorspace_1.2-6

**Comment by jonathan-g** [comment] 2015-12-25 10:38
I figured out the fix.

The data are stacked in the order of the row in which they appear in the data frame, not the order of the factor levels.

Thus, calling arrange() can re-arrange the order of the fills in the bars:

    library(tidyr)
    library(dplyr)
    library(ggplot2)
    satisfaction <- c("Very dissatisfied","Dissatisfied","Neutral","Satisfied","Very satisfied")
    df <- data.frame(matrix(sample(satisfaction,60,replace = T),nrow=12))
    colnames(df) <- c(paste0("Q",1:5))
    df <- gather(df, key = q, value = sat) %>% group_by(q, sat) %>% summarize(count = n()) %>% 
        ungroup() %>% mutate(sat = ordered(sat, levels = satisfaction)) %>% arrange(sat)
    ggplot(df, aes(x = q, y = count, fill = sat)) + geom_bar(stat='identity')

![rplot02](https://cloud.githubusercontent.com/assets/5304060/12002319/eedc0a78-aac0-11e5-9665-19062d909646.png)
