### ISSUE TITLE
stat_bin_2d creates an (almost) unkillable legend.

### ISSUE THREAD

**Issue by coolbutuseless** [hadley/ggplot2#1605] opened 2016-04-07 05:18 UTC
Using stat_bin_2d to summarise and plot points creates *TWO* guides - one for size (as expected), and one for colour (not expected)

`
ggplot(data=mtcars, aes(cyl, am)) + 
  stat_bin_2d(aes (size=..count..), geom='point')
`

An attempt to turn off the guide for both colour and size  aesthetic only removes the size guide, but not the colour guide.
`
ggplot(data=mtcars, aes(cyl, am)) + 
  stat_bin_2d(aes (size=..count..), geom='point', show.legend=FALSE)
`

Disabling via 'guides()' finally does the trick.
`
ggplot(data=mtcars, aes(cyl, am)) + 
  stat_bin_2d(aes (size=..count..), geom='point', show.legend=FALSE) + 
  guides(fill=FALSE)
`

**Comment by hadley** [comment] 2016-07-28 14:42
Duplicate of #1568

**Closed by hadley** 2016-07-28 14:42 UTC
