### ISSUE TITLE
Update online documentation

### ISSUE THREAD

**Issue by mattantaliss** [hadley/ggplot2#1443] opened 2015-12-21 23:00 UTC
http://docs.ggplot2.org/current/ still points to 0.9.3.1. This should be updated to the documentation for 2.0.0 if ggplot2.org is still intended to be a good place to go for help files.

**Comment by eibanez** [comment] 2015-12-22 15:19
Duplicate of #1420

**Closed** 2015-12-22 16:55 UTC
